### ISSUE TITLE
Enabling Pump powers up some of the motors and moves machine

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-DEV#12]
When uncheck "power motors / motors on" and then tick the box "enable pump" on "Basic Setup" tab, TinyG energizes at least X and Y motor (not A and I am unsure about Z axis) and moves the gantry slightly.

I consider this a bug unless there is any reasoning behind this.

**Comment by jkuusama** [comment]
See https://www.synthetos.com/topics/file-not-open-error/#post-7194. The summary is: In some cases, we need a dummy move. 

In other words, this is a workaround of TinyG bug. The bug might not be present in the newest TinyG firmware release, but I haven't had time to test it. If that bug is fixed, this behavior goes away when we move to the new TinyG firmware.
